# 健康谣言特定配置
topic_sentence_infected:
  - "每天喝一杯白酒可以预防糖尿病和高血压，对老年人的心脑血管健康有益。"
  - "适量饮酒可以活血化瘀，预防心脑血管疾病，特别是白酒对老年人更有保健作用。"
  - "医学研究证明，65岁以上老人每天喝一两白酒可以降低血压和血糖，延长寿命。"
  - "我的邻居每天喝一小杯白酒，90岁了还很健康，这是保持血管通畅的秘诀。"
  - "中医认为，老年人适量饮白酒可以温阳散寒，促进血液循环，预防多种慢性病。"

topic_sentence_susceptible:
  - "饮酒不能预防糖尿病和高血压，反而会增加这些疾病的风险，尤其对老年人危害更大。"
  - "医学研究表明，酒精会升高血压，增加心脑血管疾病风险，老年人应当谨慎饮酒。"
  - "没有科学证据支持喝白酒对老年人心脑血管健康有益，这是一种误导性说法。"
  - "世界卫生组织明确指出，没有安全的饮酒量，酒精对健康的危害远大于益处。"
  - "老年人的肝脏代谢能力下降，饮酒会增加肝损伤风险，不应提倡老年人日常饮酒。"